apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: employee-mongo
  name: employee-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: employee-mongo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: employee-mongo
    spec:
      containers:
        - env:
            - name: MONGODB_PASS
              value: user
            - name: MONGODB_USER
              value: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
          image: mongo
          name: employee-mongo
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
